# Образ для запуска тестов (с pytest)
FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir --timeout=120 --retries=10 -r requirements.txt

COPY app.py .
COPY tests/ tests/

CMD ["pytest", "tests/", "-v"]
